version: "3.9"

services:
  api:
    image: mini-store-api:1.0.0
    container_name: mini-api
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: mini-frontend
    ports:
      - "5500:5500"
    depends_on:
      - api
